<h1>NumPy Data Science Essentials</h1>

In [1]:
import numpy as np

Version of numpy:

In [2]:
print(np.__version__)

1.18.1


<h6>Create Array from a list:</h6>

In [3]:
mylist=[-17,0,4,5,9]
myarray_from_mylist=np.array(mylist)
myarray_from_mylist

array([-17,   0,   4,   5,   9])

In [4]:
myarray=np.array(input().split(), dtype=int)
myarray

1 2 3 4 


array([1, 2, 3, 4])

<h6>Create Array from a tuple:</h6>

In [5]:
mytuple = (-3,5,5)
myarray_from_list=np.array(mytuple)
myarray_from_list

array([-3,  5,  5])

<h6>Difference between python and numpy data structures</h6>

In [6]:
mytuple*6  #same elements are repeated 6 times

(-3, 5, 5, -3, 5, 5, -3, 5, 5, -3, 5, 5, -3, 5, 5, -3, 5, 5)

In [7]:
myarray_from_list*6  #elements are multiplied by 6

array([-18,  30,  30])

<h6> Intrinsic Numpy array creation using NumPy's methods </h6>

In [8]:
myarray=np.arange(7)   
myarray

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
myarray.size
len(myarray)
#both can be used for size/length

7

In [10]:
np.arange(10,26, step=5)

array([10, 15, 20, 25])

<h6>linspace(), zeros(), ones(), and Numpy Data Types</h6>

1)   linspace() returns evenly spaces, calculated over the interval

In [11]:
np.linspace(5,15,6) #gives 6 evenly spaced el. from 5 to 15

array([ 5.,  7.,  9., 11., 13., 15.])

2) zeros()

In [12]:
np.zeros(5)   #gives 1-D array i.e. a vector 

array([0., 0., 0., 0., 0.])

In [13]:
aa=np.ones((3,2,4)) ##passing a tuple ##gives 3 3-D array with 4 cols
aa

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
aa.ndim

3

<h6> Two Dimensional Arrays </h6>

In [15]:
my2darray=np.arange(35)  # gives 0 to 34
my2darray.shape=(7,5)    #Check syntax #will give error if product of 7,5 !=35
my2darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [16]:
my2darray.ndim

2

<h6> Three Dimensional Arrays </h6>

In [17]:
my3darray=np.arange(30)
my3darray.shape=(2,5,3)
my3darray

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [18]:
my3darray.ndim

3

<h6> Boolean Mask Arrays </h6>

In [19]:
myvector=np.array([-17,-4,0,2,21,37,105])  #revise syntax for defn array

In [20]:
zero_mod_7_mask = 0 ==(myvector%7)
zero_mod_7_mask  #if mod 7 of el is 0 then true

array([False, False,  True, False,  True, False,  True])

In [21]:
myvector[zero_mod_7_mask] #gives el with true

array([  0,  21, 105])

<h6> NumPy Logical Operators </h3>

In [22]:
mod_test=0==(myvector%7)
mod_test

array([False, False,  True, False,  True, False,  True])

In [23]:
positive_test = myvector>0   #if el is >0 return true
positive_test  

array([False, False, False,  True,  True,  True,  True])

In [24]:
combined_mask = np.logical_and(mod_test,positive_test)
combined_mask

array([False, False, False, False,  True, False,  True])

In [25]:
myvector[combined_mask]

array([ 21, 105])

<h6> Broadcasting </h6>

In [26]:
left_mat= np.arange(6).reshape((2,3)) #reshape takes a tuple
right_mat=np.arange(15).reshape((3,5))

In [27]:
np.inner(left_mat,right_mat) #their last dims must be equal

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [28]:
np.dot(left_mat,right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

<h6> Operating Along Axes </h6>

In [29]:
my3darray

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [30]:
my3darray.shape

(2, 5, 3)

In [31]:
my3darray.sum()  #gives sum of all el

435

In [32]:
my3darray.sum(axis=0)  #eliminates 0th el in shape and gives 5 by 3

array([[15, 17, 19],
       [21, 23, 25],
       [27, 29, 31],
       [33, 35, 37],
       [39, 41, 43]])

In [33]:
my3darray.sum(axis=1)  #eliminates 1st el in shape and gives 2 by 3

array([[ 30,  35,  40],
       [105, 110, 115]])

In [34]:
my3darray.sum(axis=2)  #eliminates 2nd el in shape and gives 2 by 5

array([[ 3, 12, 21, 30, 39],
       [48, 57, 66, 75, 84]])

<h6> Broadcasting Rules are tough. Missing info</h6>

<h6> Creating Structured Arrays</h6>

In [35]:
person=[('name','S6'),('height','f8'),('weight','f8'),('age','i8')]
person  #s string f float i int

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [36]:
people=np.zeros((4),dtype=person)
people

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [37]:
people[3]=('Delta',23,50,23)
people

array([(b'',  0.,  0.,  0), (b'',  0.,  0.,  0), (b'',  0.,  0.,  0),
       (b'Delta', 23., 50., 23)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [38]:
ages = people['age']

<h6> Multi-Dimensional Structured Arrays</h6>

In [39]:
people_big_array = np.zeros((4,3,2),dtype=person)
people_big_array


array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [40]:
people_big_array[1,2,1]= ('Echo',68,155,46)

In [41]:
people_big_array

array([[[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'Echo', 68., 155., 46)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [42]:
people_big_array[1]

array([[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
       [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
       [(b'',  0.,   0.,  0), (b'Echo', 68., 155., 46)]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [43]:
people_big_array[1].name #gives error. we can use rec arrays instead

AttributeError: 'numpy.ndarray' object has no attribute 'name'

<h6> Creating Record Arrays</h6>

In [44]:
person_record_array=np.rec.array([('Delta',73,205,34)],dtype=person)

In [45]:
person_record_array  #prints as a rec.array

rec.array([(b'Delta', 73., 205., 34)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [46]:
person_record_array[0]

(b'Delta', 73., 205., 34)

In [47]:
person_record_array[0].name   #this works

b'Delta'

<h6> Views and Copies </h6>

views :  provide 2/more differently named references
to the same location in memory


copy : takes data from one location in the memory and 
    stores it at another location in the memory

In [48]:
mi_casa=np.array([-45,-31,-12,0,2,25,51,99])

In [49]:
su_case=mi_casa

Reference equality

In [50]:
mi_casa is su_case

True

In [51]:
id(mi_casa)

140356663175488

In [52]:
id(su_case)

140356663175488

Value Equality

In [53]:
mi_casa==su_case

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [54]:
su_case[0]=0

In [55]:
mi_casa

array([  0, -31, -12,   0,   2,  25,  51,  99])

In [56]:
id(mi_casa)

140356663175488

In [57]:
id(su_case)

140356663175488

<h6> View : A Shallow Copy </h6>

In [58]:
tree_house=np.array([1,2,3,4,5,6])

In [59]:
farm_house=tree_house.view()

In [60]:
farm_house

array([1, 2, 3, 4, 5, 6])

In [61]:
farm_house.shape=(2,3)

In [62]:
farm_house

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
tree_house

array([1, 2, 3, 4, 5, 6])

In [64]:
tree_house[3]=400

In [65]:
farm_house

array([[  1,   2,   3],
       [400,   5,   6]])

<h6> Deep Copy </h6>

In [66]:
dog_house=np.copy(tree_house)

In [67]:
dog_house

array([  1,   2,   3, 400,   5,   6])

In [68]:
dog_house[0]=100

In [69]:
dog_house

array([100,   2,   3, 400,   5,   6])

In [70]:
tree_house

array([  1,   2,   3, 400,   5,   6])

Diff btwn views and copies : Copies duplicate data in different locations in the memory and views provide multiple references to the same location

<h6> Attributes of NumPy Arrays</h6>

In [71]:
myarray

array([0, 1, 2, 3, 4, 5, 6])

In [72]:
myarray.shape

(7,)

In [73]:
myarray.ndim

1

In [74]:
myarray.size

7

In [75]:
len(myarray)

7

In [76]:
myarray.dtype

dtype('int64')

In [77]:
myarray.itemsize #64 bit int contains 8Bytes

8

In [78]:
type(myarray)

numpy.ndarray

<h6> Adding and Removing elements from NumPy arrays </h6>

In [79]:
a=np.array(np.arange(24)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [80]:
b=np.append(a,[5,6,7,8]) 
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [81]:
b.shape

(28,)

In [82]:
b.shape=((7,4))      #a is unaffected
b              

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [83]:
c=np.array(np.arange(24)).reshape(2,3,4) *10 
c

array([[[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]],

       [[120, 130, 140, 150],
        [160, 170, 180, 190],
        [200, 210, 220, 230]]])

In [84]:
np.append(a,c,axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]],

       [[120, 130, 140, 150],
        [160, 170, 180, 190],
        [200, 210, 220, 230]]])

In [85]:
np.append(a,c,axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [120, 130, 140, 150],
        [160, 170, 180, 190],
        [200, 210, 220, 230]]])

In [86]:
np.append(a,c,axis=2)

array([[[  0,   1,   2,   3,   0,  10,  20,  30],
        [  4,   5,   6,   7,  40,  50,  60,  70],
        [  8,   9,  10,  11,  80,  90, 100, 110]],

       [[ 12,  13,  14,  15, 120, 130, 140, 150],
        [ 16,  17,  18,  19, 160, 170, 180, 190],
        [ 20,  21,  22,  23, 200, 210, 220, 230]]])

In [87]:
my_hay_stack=np.hstack((a,c))   # same as np.append(a,c,axis=1)
my_hay_stack 

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [120, 130, 140, 150],
        [160, 170, 180, 190],
        [200, 210, 220, 230]]])

<h6> Insert </h6>  

SYNTAX  :   .insert(arr,obj,values,axis) SYNTAX

In [88]:
c

array([[[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]],

       [[120, 130, 140, 150],
        [160, 170, 180, 190],
        [200, 210, 220, 230]]])

In [89]:
insertingArray=np.insert(c,1,999,axis=0)
insertingArray

array([[[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]],

       [[999, 999, 999, 999],
        [999, 999, 999, 999],
        [999, 999, 999, 999]],

       [[120, 130, 140, 150],
        [160, 170, 180, 190],
        [200, 210, 220, 230]]])

In [90]:
insertingArray=np.insert(c,1,999,axis=1)
insertingArray

array([[[  0,  10,  20,  30],
        [999, 999, 999, 999],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]],

       [[120, 130, 140, 150],
        [999, 999, 999, 999],
        [160, 170, 180, 190],
        [200, 210, 220, 230]]])

In [91]:
insertingArray=np.insert(c,1,999,axis=2)
insertingArray

array([[[  0, 999,  10,  20,  30],
        [ 40, 999,  50,  60,  70],
        [ 80, 999,  90, 100, 110]],

       [[120, 999, 130, 140, 150],
        [160, 999, 170, 180, 190],
        [200, 999, 210, 220, 230]]])

<h6> Delete</h6>

In [92]:
c

array([[[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]],

       [[120, 130, 140, 150],
        [160, 170, 180, 190],
        [200, 210, 220, 230]]])

In [93]:
deletingArray= np.delete(c,1,axis=0)
deletingArray

array([[[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110]]])

In [94]:
deletingArray= np.delete(c,1,axis=1)  #deletes 1st row of all arrays
deletingArray 

array([[[  0,  10,  20,  30],
        [ 80,  90, 100, 110]],

       [[120, 130, 140, 150],
        [200, 210, 220, 230]]])

In [95]:
deletingArray= np.delete(c,1,axis=2)  #deletes 1st col of all arrays
deletingArray 

array([[[  0,  20,  30],
        [ 40,  60,  70],
        [ 80, 100, 110]],

       [[120, 140, 150],
        [160, 180, 190],
        [200, 220, 230]]])

<h6> Joining and Splitting </h6>

concatenate, stack , split functions

In [96]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
a

array([[1, 2],
       [3, 4]])

In [97]:
b

array([[5, 6]])

In [98]:
ab=np.concatenate((a,b), axis=0)
ab

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
ab=np.concatenate((a,b), axis=1)
ab

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [100]:
ab=np.concatenate((a,b), axis=2)
ab

AxisError: axis 2 is out of bounds for array of dimension 2

In [101]:
z=np.array([[[1,2],[3,4],[5,6]]])
z

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [102]:
stack0=np.stack(z,axis=0)
stack0

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [103]:
stack0=np.stack(z,axis=1)
stack0

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [104]:
z.ndim

3

In [105]:
stack0=np.stack(z,axis=2)
stack0

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

<h3> Concatenate Array </h3>

In [106]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
a

array([[1, 2],
       [3, 4]])

In [107]:
b

array([[5, 6]])

In [108]:
ab=np.concatenate((a,b), axis=0)
ab

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
ab=np.concatenate((a,b), axis=1)
ab

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

lets check if ab is a view or a copy

In [110]:
ab[1,1]=5555
ab

array([[   1,    2],
       [   3, 5555],
       [   5,    6]])

In [111]:
a

array([[1, 2],
       [3, 4]])

5555 isnt in a. Hence ab is a copy not a view

<h3> Array Shape Manipulation </h3>


In [112]:
my_start_array=np.array(np.arange(24))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [113]:
my_start_array.shape

(24,)

In [114]:
my_3_8_array=my_start_array.reshape((3,8))
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [115]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [116]:
my_ravel_array = my_3_8_array.ravel()
my_ravel_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

we converted 3 by 8 array into a 1D array

In [117]:
my_ravel_array.shape


(24,)

In [118]:
for n in my_3_8_array.flat:
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


Array.flat is an iterator and hence can be used in a control statement

<h3> Rearranging Array Elements </h3>

<h3> fliplr "flip left right"</h3>

In [119]:
np.fliplr(my_3_8_array)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

<h3> flipud "flip up down"</h3>

In [120]:
np.flipud(my_3_8_array)

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [121]:
my_start_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [122]:
np.roll(my_start_array,5)

array([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18])

In [123]:
np.roll(my_start_array,-5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23,  0,  1,  2,  3,  4])

In [124]:
np.rot90(my_3_8_array)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [125]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

----flip up down, flip left right, roll, rotate 90---

<h3> Transpose </h3>

In [126]:
np.transpose(my_3_8_array)

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [127]:
np.transpose(my_start_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

<h3> Tiling Array </h3>

Construct an array by repeating an array n number of times givne by reps

In [131]:
another_array= np.array(np.arange(5))

In [132]:
my_tiling_array=np.tile(another_array,2)
my_tiling_array

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [137]:
my_tiling_array2=np.tile(another_array,(2,2))
my_tiling_array2

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

In [140]:
another_array[::-1]

array([4, 3, 2, 1, 0])

In [157]:
another_array=np.zeros(20)
another_array[0::5]=4

In [158]:
another_array=np.random.random(30)
another_array.mean()

0.5761862043037801

In [159]:
another_array=np.random.random(30)
another_array.mean()

0.4566454659682196

In [160]:
another_array=np.zeros((8,8),dtype='int')
another_array[1::2]

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])